# Generated by Django 4.2.5 on 2023-09-25 22:09

from django.db import migrations, models
import restbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('restbackend', '0006_alter_playareadb_playareaimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playareadb',
            name='playAreaImageUrl',
            field=models.ImageField(upload_to=restbackend.models.play_area_image_upload),
        ),
    ]
