# Generated by Django 4.2.5 on 2023-09-26 19:39

from django.db import migrations, models
import restbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('restbackend', '0007_alter_playareadb_playareaimageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorName', models.CharField(max_length=50)),
                ('VendorPhoneNo', models.IntegerField()),
                ('VendorPlayAreaName', models.CharField(max_length=100)),
                ('VendorPlayAreaSports', models.CharField(max_length=20)),
                ('VendorPlayAreaLocation', models.CharField(max_length=100)),
                ('VendorPlayAreaPrice', models.PositiveIntegerField(default=999.0)),
                ('VendorPlayAreaImageOne', models.ImageField(upload_to=restbackend.models.play_area_image_upload)),
                ('VendorPlayAreaImageTwo', models.ImageField(upload_to=restbackend.models.play_area_image_upload)),
            ],
        ),
    ]
