# Generated by Django 4.2.5 on 2023-09-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbackend', '0008_vendordb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userPhoneNo', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=254)),
                ('userFavSportsOne', models.CharField(max_length=20)),
                ('userFavSportsTwo', models.CharField(max_length=20)),
                ('userLocation', models.CharField(max_length=100)),
                ('userAge', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playareadb',
            name='playAreaVendor',
            field=models.CharField(default='Play Connect', max_length=100),
        ),
    ]
