# Generated by Django 4.2.5 on 2023-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbackend', '0010_vendordb_vendoremail_vendordb_vendorpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingPlayAreaName', models.CharField(max_length=100)),
                ('bookingPlayAreaLocation', models.CharField(max_length=100)),
                ('bookingPlayAreaDate', models.DateField()),
                ('bookingPlayAreaFromTime', models.TimeField()),
                ('bookingPlayAreaToTime', models.TimeField()),
                ('bookingPlayAreaVendor', models.CharField(max_length=100)),
                ('bookingPlayAreaUser', models.CharField(max_length=100)),
                ('bookingPlayAreaUserPhoneNo', models.IntegerField()),
            ],
        ),
    ]
