# Generated by Django 4.2.5 on 2023-09-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbackend', '0011_bookingdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUserName', models.CharField(max_length=100)),
                ('adminUserEmail', models.EmailField(max_length=254)),
                ('adminUserPhoneNo', models.IntegerField()),
                ('adminUserPassword', models.CharField(max_length=100)),
                ('adminUserLocation', models.CharField(max_length=100)),
            ],
        ),
    ]
