# Generated by Django 4.2.5 on 2023-10-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbackend', '0012_admindb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdb',
            name='bookingPlayAreaFromTime',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='bookingPlayAreaLocation',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='bookingPlayAreaToTime',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='bookingPlayAreaUserPhoneNo',
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='bookingPlayAreaSports',
            field=models.CharField(default='Cricket', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='bookingPlayAreaTime',
            field=models.CharField(default=['12AM-1AM'], max_length=100),
        ),
    ]
